### ISSUE TITLE
Suggestion regarding degrees_to_radians in 02-programs.ipynb

### ISSUE THREAD

**Issue by python33r** [IanHawke/maths-with-python#3]
`degrees_to_radians` is perhaps not the best example to use as a function definition, given that it duplicates the `radians` function already found in `math`. I think something not already in the standard library would be a bit more compelling.

**Comment by IanHawke** [comment]
This is true, but at the complexity level I'm aiming for here I can't think of an obvious alternative that's not already covered. It needs to be something that first year (first semester) UG students are comfortable with, is obviously mathematically useful, etc. Plus, I'm assuming that most won't know the standard library (note that in the classes section, the exercise on rational numbers almost exactly duplicates a standard library class!).

One of the main reasons for choosing this example was as a close mathematical analogue to SWCarpentry's fahr_to_kelvin example. I didn't want to use that as (a) it's not obviously mathematically relevant, and (b) for many of our current UG students, I don't believe they know or care about Farenheit temperatures!

Can you think of a concrete example to replace it? I'm still struggling...

**Comment by IanHawke** [comment]
Closing as I still haven't thought of a better idea.
