### ISSUE TITLE
Functions vs procedures

### ISSUE THREAD

**Issue by python33r** [IanHawke/maths-with-python#4]
With my pedantic hat on, I'm wondering whether the `degrees_to_radians_normalized` example in `03-loops-control-flow.ipynb` runs the risk of confusion between two rather different kinds of Python function: the strict mathematical function that is passed inputs and returns a result; and the procedure that is called for its side-effects (in this case, printing to stdout).

To me, your `degrees_to_radians_normalized` would be more useful as a function if it simply forced the argument to be within the range [0.0, 360.0] via modulo arithmetic or whatever and then documented this behaviour in the docstring, rather than printing anything on screen. The issue here is that functions can be called in various different contexts - including those in which there is no terminal window for the `print` function to display its output! Also, there will be situations in which we want function calls to be 'silent', even if there is a terminal window in which output can appear.

You could still illustrate the application of `if` statements by having a separate function `check_angle` that displays information about the appropriateness of the angle:

``` python
def check_angle(angle):
    if angle < 0.0:
        print("Angle should not be < 0")
    elif angle > 360.0:
        print("Angle should not be > 360")
    else:
        print("Angle OK")
```

This just acts as a procedure that generates printed output and doesn't return anything. Obviously this is less generally useful than a 'pure' mathematical function, as it requires there to be somewhere where output will be displayed.

**Comment by IanHawke** [comment]
This makes sense to me, and commit c352296b411af9a78be4a25464dfe5bdd996019e should address this. It's still not an ideal solution as the check function returns a boolean and prints, but I hope balances clarity and simplicity. What do you think?

**Comment by IanHawke** [comment]
Closing as I can't think how to improve latest version.
