### ISSUE TITLE
Various issues and mistakes

### ISSUE THREAD

**Issue by SamMugel** [IanHawke/maths-with-python#7]
First off, the numbering of the LateX document and of the sections in the ipython notebook differ, which may lead to confusions.

_part 02-programs_
- section Scope: %reset command looks like something that should be typed into the ipython notebook. As we have only just discussed usage of spyder this may be somewhat confusing.
- sections Printing and strings and Strings: two apparently different definitions of what a method is are given. The explanations concerning methods are somewhat confusing.
- Floating point numbers, Exercise 2:

Show that, if $a = 10^{-n} = c$ and $b = 10^n$ then

\begin{equation}
  x = \frac{10^{2 n}}{2} \left( -1 \pm \sqrt{1 - 4 \* 10^{-4n}} \right).
\end{equation}

(missing factor of 4)
- Floating point numbers, Exercises 2 and 3: it is not very clear what we are meant to do in these exercises. Perhaps specify these are not python exercises?
# ----------------------------------------------------------------------

_03-loops-control-flow_
- section _Breakpoints_: need to be a lot clearer here in the list of instructions for debugging.
  - _This is performed in the code within the for loop, which starts on line 32 of the code._
    For me this is line 36 due to the header. Could you insert line numbering in your copy of the function in the ipython notebook?
  - 1. _open code in spyder_
    Which code? breakpoint.py or the file containing *import breakpoints ... *?
  - 4. _... The console will indicate that ..._
    This entry would be more useful if it provided the exact statement that the console should return.
  - When I ran debug/debug, I expected the code to evaluate until the breakpoint. Instead, it evaluated line by line. The result was that I had to run either step or step into several times before variables started appearing in my variable explorer and this confused me. I think the issue here is that I was confused by point 5. and 6.

**Comment by IanHawke** [comment]
- The difference between the notebook numbering and the pdf may cause issues and I need to think about. However, I'm not planning on using notebooks with students.
- `%reset` is an IPython command and will work in the console.
- Will check the methods part.
- Will check the exercise.
- On line numbers I'll try and be more specific - it's not possible AFAIK to get this into the listing automagically.
- I'll look through the debugging bit again. This may need direct demonstration.

**Comment by SamMugel** [comment]
I don't really understand in Exercise 5

Modify your functions so that, instead of returning whether a point is inside the set or not, it returns the logarithm of the number of iterations it takes. Plot the result using `imshow` again.

It seemed to me that we had fixed the number of iterations to N=100?

**Comment by josh-gree** [comment]
I think the idea is that N=100 is the hard limit - if it takes this number of iterations without the modulus becoming greater than 2 then you can assume it lies in the set. If at iteration n < N the modulus of z is greater than 2, at which point you stop iterating, then it does not lie in the set and by returning log(n) you get some idea of how quickly that point leaves the set...

**Comment by IanHawke** [comment]
That's exactly it; most of the time it will exit after <10 iterations.

On Wed, Sep 16, 2015 at 7:48 PM, Joshua Greenhalgh <notifications@github.com

**Comment by IanHawke** [comment]
I'm going to close this after 58dd2614238654dfda4375797a7bdc6eadf971de . The comments around the discussion of breakpoints and debugging still need addressing, but I think we'll need more experience in seeing what causes trouble for real students before we can easily tidy this up.
